---
groups:
  - name: bosh-global-net
    jobs:
      - unit-1.9
      - unit-2.1
      - integration-1.9-mysql
      - integration-1.9-postgres
      - integration-2.1-mysql
      - integration-2.1-postgres

jobs:
  - name: unit-1.9
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 2.1.6

  - name: integration-1.9-mysql
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 1.9.3

  - name: integration-1.9-postgres
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9], get: bosh-src}

      - task: test
        privileged: true
        file:  bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 1.9.3

  - name: integration-2.1-mysql
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 2.1.6

  - name: integration-2.1-postgres
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 2.1.6

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: global-net
